version: 1
name: "Polling-App CodeRabbit Config"
language: typescript
framework: nextjs

# Trigger checks on pull requests
on:
  pull_request: true

# Define which rules to run
checks:
  - name: "default"
    rules:
      - code-style
      - tailwind-shadcn
      - supabase-security
      - server-actions
      - typecheck-build
      - security-scan

# Project-specific rules
rules:
  - id: code-style
    name: "Code Style & Lint"
    description: "Ensure code follows ESLint/Prettier rules and conventions in project_rules.md."
    severity: warning
    always_apply: true

  - id: tailwind-shadcn
    name: "Tailwind & shadcn/ui Usage"
    description: "Check Tailwind utility usage and shadcn/ui components. Ensure imports like tailwind-merge and @radix-ui/* are present when used."
    severity: warning

  - id: supabase-security
    name: "Supabase & Secrets"
    description: "Detect hardcoded Supabase keys or secrets. Enforce use of env vars and `/lib/supabase.ts` for DB/auth calls."
    severity: error

  - id: server-actions
    name: "Server Actions & App Router"
    description: "Prefer Server Components and Next.js Server Actions for mutations. Flag client-side fetches in page components."
    severity: warning

  - id: typecheck-build
    name: "Type Checking & Build"
    description: "Run `npm run typecheck` and `npm run build`. Report any failures."
    severity: error

  - id: security-scan
    name: "Security Scan"
    description: "Scan for secrets and vulnerable dependencies. Recommend `npm audit` if issues are found."
    severity: error

# Reviewer metadata
metadata:
  contact: "azukauteh"
  recommended_branch: "chore/add-coderabbit-config"
  docs: "./polling_app_rules.md"
